# https://gist.github.com/gnarf/b103e77f37236ca72d8e
# SOURCE: \cat roles/*/vagrant-config.yml | pbcopy
:vms:
  zsh-ci:
    :hostname: "zsh-ci"
    :name: "zsh-ci"
    :type: "master"
    :box: "ubuntu/bionic64"
    :eth1: "192.168.10.15"
    :ip: "192.168.10.15"
    :mem: 2048
    :ram: 2048
    :cpu: 2
    :id: 10
