---
- name: Reset antigen cache
  command: "{{ bossjones__oh__my__zsh__path_to_shell }} -c 'source {{ bossjones__oh__my__zsh__config }}; antigen reset'"
  become: yes
  become_user: "{{ bossjones__oh__my__zsh__user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  command: "{{ bossjones__oh__my__zsh__path_to_shell }} -c 'source {{ bossjones__oh__my__zsh__config }}; antigen update'"
  become: yes
  become_user: "{{ bossjones__oh__my__zsh__user }}"
  changed_when: false
  failed_when: false
